### ISSUE TITLE
Rails/UniqueValidationWithoutIndex

### ISSUE THREAD

**Issue by shannonfuit** [youngcapital/rubocopital#67]
# Rails/UniqueValidationWithoutIndex

Enabled by default | Safe | Supports autocorrection | VersionAdded | VersionChanged
-- | -- | -- | -- | --
Enabled | Yes | No | 2.5 | -

When you define a uniqueness validation in Active Record model, you also should add a unique index for the column. There are two reasons First, duplicated records may occur even if Active Record’s validation is defined. Second, it will cause slow queries. The validation executes a SELECT statement with the target column when inserting/updating a record. If the column does not have an index and the table is large, the query will be heavy.

Note that the cop does nothing if db/schema.rb does not exist.

### Examples
```ruby
# bad - if the schema does not have a unique index
validates :account, uniqueness: true

# good - if the schema has a unique index
validates :account, uniqueness: true

# good - even if the schema does not have a unique index
validates :account, length: { minimum: MIN_LENGTH }
```
### Configurable attributes

Name | Default value | Configurable values
-- | -- | --
Include | app/models/*/.rb | Array

**Comment by xtr3me** [comment]
Will this work without issues when using active support validations without activerecord?

**Comment by risc12** [comment]
@xtr3me It seems like the cop checks if the table exists and otherwise returns nil ([Link to MR](https://github.com/rubocop-hq/rubocop-rails/pull/197/files#diff-af4cb6c7e18c12f0a26b2ef45466f731R48)).

So if you use it without ActiveRecord it will probably not be able to find the table and therefore fail. It seems by the way that "validates_uniqueness_of" is part of ActiveModel, not ActiveSupport: https://apidock.com/rails/v2.3.8/ActiveModel/Validations/ClassMethods/validates_uniqueness_of
